package com.peakform.fitness.core

import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.put
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * ShareText — legacy generateWorkoutShareText (PF L46974–46990) + copyWorkoutLink
 * user-signal summary (L46991+). QR payload embeds the same text (local ZXing render).
 */
object ShareText {

    /** 🏋️ WORKOUT / 📅 Date / 🔗 Link / 📋 EXERCISES / 💪 signature — legacy format. */
    fun workoutShareText(w: WorkoutRecord, appUrl: String = "https://try4ever.com/fitness"): String {
        val date = try {
            SimpleDateFormat("EEEE, MMMM d, yyyy", Locale.US).format(Date(ProState.utcDayMillis(w.date)))
        } catch (_: Exception) { w.date }
        val sb = StringBuilder()
        sb.append("🏋️ WORKOUT: ").append(w.name.ifBlank { "Training Session" }).append("\n")
        sb.append("📅 Date: ").append(date).append("\n")
        sb.append("🔗 Link: ").append(appUrl).append("\n")
        sb.append("📋 EXERCISES:\n")
        w.exercises.filter { !it.isWarmup && !it.isCooldown }.forEachIndexed { i, ex ->
            val muscles = ex.muscleGroup.joinToString(", ")
            sb.append("  ${i + 1}. ").append(ex.name)
            if (muscles.isNotBlank()) sb.append(" – ").append(muscles)
            sb.append("\n")
        }
        sb.append("💪 Generated by Pro Fitness App")
        return sb.toString()
    }

    /** copyWorkoutLink's extra user-signal block (experience, streak, deload, trend). */
    fun userSignalSummary(): String {
        val d = ProState.data
        val streak = com.peakform.fitness.engine.Stats.calculateStreak()
        val exp = d.user.experience.replaceFirstChar { it.uppercase() }.ifBlank { "Beginner" }
        val sb = StringBuilder()
        sb.append("👤 $exp athlete")
        if (streak > 0) sb.append(" · $streak day streak")
        val deload = d.workouts.lastOrNull { it.isDeload && it.isCompleted }
        if (deload != null) sb.append(" · deload week")
        val improving = com.peakform.fitness.engine.Stats.calculateOverallStrengthProgress() > 0.0
        sb.append(" · key lifts ").append(if (improving) "trending up 📈" else "holding steady")
        return sb.toString()
    }

    /** QR payload (the legacy app encoded the app URL; native encodes the share text so scans are useful offline). */
    fun qrPayload(w: WorkoutRecord): String = workoutShareText(w)
}
